# Generated by Django 4.1.5 on 2023-03-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_cardspage_card_subtitle_cardspage_card_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cardspage",
            name="max_recommended_age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
